CREATE TABLE public.alembic_version (
    version_num character varying(32) NOT NULL
);
CREATE TABLE public.contract_recurring_payments (
    id bigint NOT NULL,
    contract_id integer NOT NULL,
    cycle_number integer NOT NULL,
    period_label text NOT NULL,
    period_year integer NOT NULL,
    period_month integer NOT NULL,
    original_amount numeric(18,2) NOT NULL,
    amount numeric(18,2) NOT NULL,
    status text DEFAULT 'PENDING'::text NOT NULL,
    paid_at timestamp with time zone,
    notes text,
    created_by text,
    updated_by text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_contract_recurring_payments_cycle_number CHECK ((cycle_number >= 1)),
    CONSTRAINT ck_contract_recurring_payments_period_month CHECK (((period_month >= 1) AND (period_month <= 12))),
    CONSTRAINT ck_contract_recurring_payments_period_year CHECK (((period_year >= 2000) AND (period_year <= 2100))),
    CONSTRAINT ck_contract_recurring_payments_status CHECK ((status = ANY (ARRAY['PENDING'::text, 'DUE'::text, 'OVERDUE'::text, 'PAID'::text, 'CANCELLED'::text])))
);
CREATE TABLE public.contract_term_payments (
    id bigint NOT NULL,
    contract_id integer NOT NULL,
    termin_number integer NOT NULL,
    period_label text NOT NULL,
    period_year integer NOT NULL,
    period_month integer NOT NULL,
    original_amount numeric(18,2) NOT NULL,
    amount numeric(18,2) NOT NULL,
    status text DEFAULT 'PENDING'::text NOT NULL,
    paid_at timestamp with time zone,
    notes text,
    created_by text,
    updated_by text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_contract_term_payments_period_month CHECK (((period_month >= 1) AND (period_month <= 12))),
    CONSTRAINT ck_contract_term_payments_period_year CHECK (((period_year >= 2000) AND (period_year <= 2100))),
    CONSTRAINT ck_contract_term_payments_status CHECK ((status = ANY (ARRAY['PENDING'::text, 'DUE'::text, 'OVERDUE'::text, 'PAID'::text, 'CANCELLED'::text]))),
    CONSTRAINT ck_contract_term_payments_termin_number CHECK ((termin_number >= 1))
);
CREATE TABLE public.contracts (
    id integer NOT NULL,
    source_job_id integer NOT NULL,
    file_id integer NOT NULL,
    final_data jsonb NOT NULL,
    version integer,
    confirmed_by character varying,
    confirmed_at timestamp with time zone DEFAULT now(),
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    customer_name character varying(500),
    customer_npwp character varying(50),
    period_start date,
    period_end date,
    service_connectivity integer DEFAULT 0 NOT NULL,
    service_non_connectivity integer DEFAULT 0 NOT NULL,
    service_bundling integer DEFAULT 0 NOT NULL,
    payment_method character varying(20),
    termin_count integer,
    installation_cost numeric(18,2) DEFAULT '0'::numeric NOT NULL,
    annual_subscription_cost numeric(18,2) DEFAULT '0'::numeric NOT NULL,
    total_contract_value numeric(18,2) DEFAULT '0'::numeric NOT NULL,
    customer_address text,
    rep_name text,
    rep_title text,
    customer_contact_name text,
    customer_contact_title text,
    customer_contact_email text,
    customer_contact_phone text,
    period_start_raw text,
    period_end_raw text,
    telkom_contact_name text,
    telkom_contact_title text,
    telkom_contact_email text,
    telkom_contact_phone text,
    payment_description text,
    termin_total_count integer,
    termin_total_amount numeric(18,2),
    payment_raw_text text,
    termin_payments_raw jsonb,
    extraction_timestamp timestamp with time zone,
    contract_processing_time_sec double precision,
    recurring_monthly_amount numeric(18,2) DEFAULT '0'::numeric NOT NULL,
    recurring_month_count integer,
    recurring_total_amount numeric(18,2) DEFAULT '0'::numeric NOT NULL,
    contract_number character varying(100)
);
CREATE TABLE public.export_history (
    id integer NOT NULL,
    contract_id integer NOT NULL,
    export_target public.exporttarget NOT NULL,
    export_path character varying,
    status character varying,
    notes text,
    exported_at timestamp with time zone DEFAULT now()
);
CREATE TABLE public.extraction_logs (
    id integer NOT NULL,
    job_id integer NOT NULL,
    level character varying NOT NULL,
    message text NOT NULL,
    details jsonb,
    created_at timestamp with time zone DEFAULT now()
);
CREATE TABLE public.files (
    id integer NOT NULL,
    original_filename character varying NOT NULL,
    size_bytes bigint NOT NULL,
    mime_type character varying NOT NULL,
    uploaded_at timestamp with time zone DEFAULT now(),
    pdf_path character varying NOT NULL
);
CREATE TABLE public.processing_jobs (
    id integer NOT NULL,
    file_id integer NOT NULL,
    status public.jobstatus NOT NULL,
    extracted_data jsonb,
    edited_data jsonb,
    ocr_artifacts jsonb,
    error_message text,
    processing_started_at timestamp with time zone,
    processing_completed_at timestamp with time zone,
    processing_time_seconds double precision,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    reviewed_by character varying,
    reviewed_at timestamp with time zone
);